import type { Metadata } from "next";
import "@/app/_style/dashboard/index.scss";
import NavBar from "@/app/_components/navbar/NavBar";
import { magra } from "@/app/_font/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={magra.className}>
      <body>
        <NavBar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
